// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapopstate.proto

package org.apache.flink.statefun.examples.datastream;

public interface MapOperatorStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vt.MapOperatorState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 vTimestamp = 2;</code>
   */
  java.util.List<java.lang.Integer> getVTimestampList();
  /**
   * <code>repeated int32 vTimestamp = 2;</code>
   */
  int getVTimestampCount();
  /**
   * <code>repeated int32 vTimestamp = 2;</code>
   */
  int getVTimestamp(int index);
}
