// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reduceopstate.proto

package org.apache.flink.statefun.examples.datastream;

public final class Reduceopstate {
  private Reduceopstate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vt_ReduceOperatorState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vt_ReduceOperatorState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vt_ReduceOperatorState_InputCountsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vt_ReduceOperatorState_InputCountsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vt_ReduceOperatorState_OutputCountsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vt_ReduceOperatorState_OutputCountsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023reduceopstate.proto\022\002vt\"\276\002\n\023ReduceOper" +
      "atorState\022\021\n\twordCount\030\001 \001(\005\022\022\n\nvTimesta" +
      "mp\030\002 \003(\005\022=\n\013InputCounts\030\003 \003(\0132(.vt.Reduc" +
      "eOperatorState.InputCountsEntry\022?\n\014Outpu" +
      "tCounts\030\004 \003(\0132).vt.ReduceOperatorState.O" +
      "utputCountsEntry\022\027\n\014OperatorType\030\005 \001(\005:\001" +
      "3\0322\n\020InputCountsEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005va" +
      "lue\030\002 \001(\005:\0028\001\0323\n\021OutputCountsEntry\022\013\n\003ke" +
      "y\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001B1\n-org.apache" +
      ".flink.statefun.examples.datastreamP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vt_ReduceOperatorState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vt_ReduceOperatorState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vt_ReduceOperatorState_descriptor,
        new java.lang.String[] { "WordCount", "VTimestamp", "InputCounts", "OutputCounts", "OperatorType", });
    internal_static_vt_ReduceOperatorState_InputCountsEntry_descriptor =
      internal_static_vt_ReduceOperatorState_descriptor.getNestedTypes().get(0);
    internal_static_vt_ReduceOperatorState_InputCountsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vt_ReduceOperatorState_InputCountsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_vt_ReduceOperatorState_OutputCountsEntry_descriptor =
      internal_static_vt_ReduceOperatorState_descriptor.getNestedTypes().get(1);
    internal_static_vt_ReduceOperatorState_OutputCountsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vt_ReduceOperatorState_OutputCountsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
