// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reduceopstate.proto

package org.apache.flink.statefun.examples.datastream;

public interface ReduceOperatorStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vt.ReduceOperatorState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 wordCount = 1;</code>
   */
  boolean hasWordCount();
  /**
   * <code>optional int32 wordCount = 1;</code>
   */
  int getWordCount();

  /**
   * <code>repeated int32 vTimestamp = 2;</code>
   */
  java.util.List<java.lang.Integer> getVTimestampList();
  /**
   * <code>repeated int32 vTimestamp = 2;</code>
   */
  int getVTimestampCount();
  /**
   * <code>repeated int32 vTimestamp = 2;</code>
   */
  int getVTimestamp(int index);
}
