// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sinkopstate.proto

package org.apache.flink.statefun.examples.datastream;

public final class Sinkopstate {
  private Sinkopstate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vt_SinkOperatorState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vt_SinkOperatorState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vt_SinkOperatorState_InputCountsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vt_SinkOperatorState_InputCountsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vt_SinkOperatorState_OutputCountsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vt_SinkOperatorState_OutputCountsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021sinkopstate.proto\022\002vt\"\261\002\n\021SinkOperator" +
      "State\022\n\n\002ID\030\001 \001(\005\022\022\n\nvTimestamp\030\002 \003(\005\022;\n" +
      "\013InputCounts\030\003 \003(\0132&.vt.SinkOperatorStat" +
      "e.InputCountsEntry\022=\n\014OutputCounts\030\004 \003(\013" +
      "2\'.vt.SinkOperatorState.OutputCountsEntr" +
      "y\022\027\n\014OperatorType\030\005 \001(\005:\0014\0322\n\020InputCount" +
      "sEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001\0323" +
      "\n\021OutputCountsEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005valu" +
      "e\030\002 \001(\005:\0028\001B1\n-org.apache.flink.statefun" +
      ".examples.datastreamP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vt_SinkOperatorState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vt_SinkOperatorState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vt_SinkOperatorState_descriptor,
        new java.lang.String[] { "ID", "VTimestamp", "InputCounts", "OutputCounts", "OperatorType", });
    internal_static_vt_SinkOperatorState_InputCountsEntry_descriptor =
      internal_static_vt_SinkOperatorState_descriptor.getNestedTypes().get(0);
    internal_static_vt_SinkOperatorState_InputCountsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vt_SinkOperatorState_InputCountsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_vt_SinkOperatorState_OutputCountsEntry_descriptor =
      internal_static_vt_SinkOperatorState_descriptor.getNestedTypes().get(1);
    internal_static_vt_SinkOperatorState_OutputCountsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vt_SinkOperatorState_OutputCountsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
