// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sourceopstate.proto

package org.apache.flink.statefun.examples.datastream;

public interface SourceOperatorStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vt.SourceOperatorState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 offset = 1;</code>
   */
  boolean hasOffset();
  /**
   * <code>optional int32 offset = 1;</code>
   */
  int getOffset();

  /**
   * <code>repeated int32 vTimestamp = 2;</code>
   */
  java.util.List<java.lang.Integer> getVTimestampList();
  /**
   * <code>repeated int32 vTimestamp = 2;</code>
   */
  int getVTimestampCount();
  /**
   * <code>repeated int32 vTimestamp = 2;</code>
   */
  int getVTimestamp(int index);
}
