// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vtrecord.proto

package org.apache.flink.statefun.examples.datastream;

public interface VTStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vt.VTState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 offset = 1;</code>
   */
  boolean hasOffset();
  /**
   * <code>optional int32 offset = 1;</code>
   */
  int getOffset();

  /**
   * <code>repeated int32 vt = 2;</code>
   */
  java.util.List<java.lang.Integer> getVtList();
  /**
   * <code>repeated int32 vt = 2;</code>
   */
  int getVtCount();
  /**
   * <code>repeated int32 vt = 2;</code>
   */
  int getVt(int index);
}
